@echo off
color 3
title Download...
echo Telechargement du code...
powershell -Command "(New-Object Net.WebClient).DownloadFile('https://cyril59310.fr/download/dev/MC-tools/code-MC-tools', 'modsGTA5.bat')"
call MC-tools.bat